apiVersion: v1
kind: Service
metadata:
  name: spring-boot-app-service
spec:
  type: NodePort
  ports:
  - name: http
    port: 80
    targetPort: 8082
    nodePort: 30080  # <-- Fixed NodePort
    protocol: TCP
  selector:
    app: spring-boot-app
